### PR TITLE
Add `Version.canonicalizedVersion` to help scrub leading zeros.

### PR DESCRIPTION
**Pull request by jonasfj**
Alternatively we could do: https://github.com/dart-lang/pub_semver/pull/34, though this is rather breaking.

### CODE REVIEW

**Comment by natebosch** [comment]
Is this something we need to move forward with before the migration to null safety (which may block publishing for a while) or can we wait on this?

**Comment by jonasfj** [comment]
We should probably have merged these for null-safety -- I think we totally forgot.

I propose that we ship this https://github.com/dart-lang/pub_semver/pull/49 in a 2.1.0 release.

**Review by sigurdm — APPROVED** [review]
LGTM

**Review by natebosch — APPROVED** [review]

**Review by sigurdm — APPROVED** [review]
LGTM

**Pull request merged**
